- platform: template
  sensors:
    washing_machine_status:
      delay_off:
        minutes: 5
      value_template: >-
        {{ states("sensor.gosund_presa02_energy_power")|float > 3.0 }}
    dryer_machine_status:
      delay_off:
        minutes: 5
      value_template: >-
        {{ states("sensor.gosund_presa01_energy_power")|float > 6.1 }}
