homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Rome
  # External access
  internal_url: !secret http_internal_url
  external_url: !secret http_public_url

  # Customization file
  customize: !include customize.yaml


# Enables configuration UI
config:

# Enables mobile app integration
mobile_app:

# Enables Lovelace UI
lovelace:
  mode: yaml
  resources:
    - url: /local/multiple-entity-row.js?v=3.4.0
      type: module

# Enables System Health component
system_health:

# Public access to HA
http:

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Enable logger and ignore events lower than critical for specified components
logger:
  default: warning
  logs:
    homeassistant.components.media_player.plex: critical

# Enable and use FFMPEG installed on system
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Cloud
cloud:

# MQTT
mqtt:
  discovery: true
  broker: !secret mqtt_broker_url
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enables HomeKit integration
homekit:
  filter:
    include_entities:
      - light.book_light
      - light.shelly_shsw_1_f431b1
      - switch.050407552462ab207ec1
      - switch.sonoff_10001f9bcf
  entity_config:
    light.book_light:
      name: Luce libro
    light.shelly_shsw_1_f431b1:
      name: Luce giardino
    switch.050407552462ab207ec1:
      name: Deumidificatore
    switch.sonoff_10001f9bcf:
      name: Albero di Natale

# Enables Alexa integration
alexa:
  smart_home:
    filter:
      include_entities:
        - light.lampada_sala
        - light.shelly_shsw_1_f431b1
    entity_config:
      light.lampada_sala:
        name: Luce sala
        description: Lampada salotto
        display_categories: LIGHT
      light.shelly_shsw_1_f431b1:
        name: Luce giardino
        display_categories: LIGHT

# Enables Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_chat_andrea 
      - !secret telegram_chat_erica
      - !secret telegram_chat_home

# Enables Cast devices
cast:

# Enables IP cameras
camera:
  - platform: yi
    name: Soggiorno
    host: !secret ip_mi_camera
    password: !secret yi_camera_password

# Enables Vacuum integration
vacuum:
  - platform: xiaomi_miio
    name: mi_roborock
    host: !secret ip_xiaomi_robot
    token: !secret mi_vacuum_token

# Enables IKEA Tradfri integration
tradfri:
  host: !secret ip_ikea_tradfri

# Shelly custom integration
shelly:
  cloud_auth_key: !secret shelly_key
  cloud_server: !secret shelly_server
  devices:
    - id: "F431B1"
      name: "Luce giardino"
      light_switch: true

# Lights
light:
  - platform: template
    lights:
      book_light: # Simulate a light for the Sonoff connected inside the Book
        value_template: "{{ is_state('switch.sonoff_10004cf9ff', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: switch.sonoff_10004cf9ff
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: switch.sonoff_10004cf9ff

# Enables IFTTT
ifttt:
  key: !secret ifttt_key

# Define custom REST Api
rest_command:
  pushcut_notification:
    url: 'https://api.pushcut.io/v1/notifications/{{ name }}'
    method: POST
    content_type: application/json
    headers:
      API-Key: !secret pushcut_api_key
    payload: '{{ payload }}'

# Persons and trackers
person:
  - name: Andrea
    id: andrea01
    user_id: 601d2c477e7a4d4f897601d21e69235f
    device_trackers:
      - device_tracker.iphoneandrea
  - name: Erica
    id: erica01
    device_trackers:
      - device_tracker.iphoneerica

device_tracker:
  - platform: ping
    interval_seconds: 20
    consider_home: 180
    hosts:
      iphoneandrea: !secret ip_iphoneandrea
      ipadandrea: !secret ip_ipadandrea
      iphoneerica: !secret ip_iphoneerica
      ipaderica: !secret ip_ipaderica

# Helper sensors
input_boolean:
  waterflood_laundry:
    name: Sensore allagamento lavanderia

#### Custom components ####

# Custom Component - Home Recycling management
home_recycling:
  calendar: /config/custom_components/home_recycling/home_recycling_calendar.json

# Custom Component - MagPi issues downloader
magpi_downloader:
  config_file: /config/custom_components/magpi_downloader/magpi_downloader_config.json
  output_path: /magpi

# Custom Component - Sonoff integration (https://github.com/peterbuga/HASS-sonoff-ewelink)
sonoff:
  username: !secret ewelink_username
  password: !secret ewelink_password


#### Other files #### 

sensor: !include sensors.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensors.yaml
remote: !include remotes.yaml
notify: !include notifications.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
