homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Rome

  # Customization file
  customize: !include customize.yaml


# Enables configuration UI
config:

# Enable System Health component
system_health:

# Public access to HA
http:
  base_url: !secret http_public_url

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Enable logger and ignore events lower than critical for specified components
logger:
  default: warning
  logs:
    homeassistant.components.media_player.plex: critical

# Enable and use FFMPEG installed on system
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Cloud
cloud:

# Enable Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_chat_andrea 
      - !secret telegram_chat_erica
      - !secret telegram_chat_home

# Configure Media Players
media_player:
  - platform: samsungtv
    name: TV Salotto
    host: !secret ip_tv_salotto
    mac: !secret mac_tv_samsung
    port: 8001
  - platform: plex

# Enable Cast devices
cast:
  media_player:
    - host: !secret ip_chromecast_cucina
    - host: !secret ip_google_home

# Enable IP cameras
camera:
  - platform: yi
    name: Soggiorno
    host: !secret ip_mi_camera
    password: !secret yi_camera_password

# Enable Vacuum integration
vacuum:
  - platform: xiaomi_miio
    name: mi_roborock
    host: !secret ip_xiaomi_robot
    token: !secret mi_vacuum_token

# Enable IKEA Tradfri integration
tradfri:
  host: !secret ip_ikea_tradfri

light:
  - platform: template
    lights:
      book_light: # Simulate a light for the Sonoff connected inside the Book
        value_template: "{{ is_state('switch.sonoff_10004cf9ff', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: switch.sonoff_10004cf9ff
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: switch.sonoff_10004cf9ff

# Enable IFTTT
ifttt:
  key: !secret ifttt_key

# Persons and trackers
person:
  - name: Andrea
    id: andrea01
    device_trackers:
      - device_tracker.iphoneandrea
  - name: Erica
    id: erica01
    device_trackers:
      - device_tracker.iphoneerica

device_tracker:
  - platform: ping
    interval_seconds: 20
    consider_home: 180
    hosts:
      iphoneandrea: !secret ip_iphoneandrea
      ipadandrea: !secret ip_ipadandrea
      iphoneerica: !secret ip_iphoneerica
      ipaderica: !secret ip_ipaderica

#### Custom components ####

# Custom Component - Home Recycling management
home_recycling:
  calendar: /config/custom_components/home_recycling/home_recycling_calendar.json

# Custom Component - MagPi issues downloader
magpi_downloader:
  config_file: /config/custom_components/magpi_downloader/magpi_downloader_config.json
  output_path: /magpi

# Custom Component - Sonoff integration (https://github.com/peterbuga/HASS-sonoff-ewelink)
sonoff:
  username: !secret ewelink_username
  password: !secret ewelink_password


#### Other files #### 

sensor: !include sensors.yaml
remote: !include remotes.yaml
notify: !include notifications.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
