homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Rome

  # Customization file
  customize: !include customize.yaml


# Show links to resources in log and frontend
#introduction:

# Enables configuration UI
config:

# Public access to HA
http:
  api_password: !secret http_password
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
  base_url: !secret http_public_url
  ssl_key: !secret http_ssl_key
  ssl_certificate: !secret http_ssl_certificate

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: dht
    sensor: DHT11
    pin: 15
    monitored_conditions:
      - temperature
      - humidity
  - platform: command_line
    name: ssl_cert_expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/homebubi.duckdns.org/cert.pem | awk '{ print $NF }'"
  - platform: systemmonitor
    resources:
      - type: since_last_boot
      - type: memory_use_percent
      - type: disk_use_percent
      - type: load_5m
      - type: network_out
      - type: network_in
      - type: processor_use

input_boolean:
  sonoff_1:
    name: Sonoff #1
    initial: off

binary_sensor:
  - platform: template
    sensors:
      sonoff_1:
        device_class: light
        value_template: "{{ states.input_boolean.sonoff_1.state == 'on' }}"
        entity_id: input_boolean.sonoff_1
      home_recycling_empty:
        friendly_name: 'Domani niente spazzatura!'
        icon_template: mdi:thumb-up
        value_template: "{{ is_state('home_recycling.empty', 'yes') }}"
      home_recycling_secco:
        friendly_name: 'Secco'
        value_template: "{{ is_state('home_recycling.secco', 'yes') }}"
      home_recycling_organico:
        friendly_name: 'Umido'
        value_template: "{{ is_state('home_recycling.organico', 'yes') }}"
      home_recycling_carta:
        friendly_name: 'Carta'
        value_template: "{{ is_state('home_recycling.carta', 'yes') }}"
      home_recycling_vetro:
        friendly_name: 'Vetro'
        value_template: "{{ is_state('home_recycling.vetro', 'yes') }}"
      home_recycling_plastica:
        friendly_name: 'Plastica'
        value_template: "{{ is_state('home_recycling.plastica', 'yes') }}"
      home_recycling_barattolame:
        friendly_name: 'Barattolame'
        value_template: "{{ is_state('home_recycling.barattolame', 'yes') }}"
  - platform: command_line
    name: port_forwarding_https
    command: 'nmap -p 443 homebubi.duckdns.org | grep open &> /dev/null && echo success || echo fail'
    payload_on: 'success'
    payload_off: 'fail'
    scan_interval: 3600
  - platform: command_line
    name: port_forwarding_http
    command: 'nmap -p 10080 homebubi.duckdns.org | grep open &> /dev/null && echo success || echo fail'
    payload_on: 'success'
    payload_off: 'fail'
    scan_interval: 3600

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Enable iOS App
#ios:

# Gestione spazzatura
home_recycling:
  calendar: /home/homeassistant/.homeassistant/custom_components/home_recycling_calendar.json

# Downloader MagPi
magpi_downloader:
  config_file: /home/homeassistant/.homeassistant/custom_components/magpi_downloader_config.json
  output_path: /home/homeassistant/magpi

# configurazione bot Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_chat_andrea 
      - !secret telegram_chat_erica
      - !secret telegram_chat_home

# Notifiche
notify:
  - name: andrea_telegram
    platform: telegram
    chat_id: !secret telegram_chat_andrea
  - name: home_telegram
    platform: telegram
    chat_id: !secret telegram_chat_home

media_player:
  - platform: plex
  - platform: samsungtv
    name: TV Salotto
    host: 192.168.1.97
    mac: !secret mac_address_tv_samsung
    port: 8001

camera:
  - platform: yi
    name: Soggiorno
    host: '192.168.1.96'
    password: !secret yi_camera_password

# IFTTT
ifttt:
  key: !secret ifttt_key

# Shell commands
shell_command:
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
