- platform: template
  lights:
    book_lamp: # Simulate a light for the Sonoff connected inside the Book
      value_template: "{{ is_state('switch.sonoff_10004cf9ff', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
          entity_id: switch.sonoff_10004cf9ff
      turn_off:
        service: homeassistant.turn_off
        data:
          entity_id: switch.sonoff_10004cf9ff
    garden: # Create a lights for Shelly switch (garden)
      value_template: "{{ is_state('switch.shelly1_f431b1', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
          entity_id: switch.shelly1_f431b1
      turn_off:
        service: homeassistant.turn_off
        data:
          entity_id: switch.shelly1_f431b1

# Ikea Tradfri bulb via Zigbee2MQTT
- platform: "mqtt"
  unique_id: office_lamp
  name: office_lamp
  state_topic: "zigbee2mqtt/ikea_tradfri_bulb_001"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  color_temp: true
  xy: false
  hs: false
  schema: "json"
  command_topic: "zigbee2mqtt/ikea_tradfri_bulb_001/set"
  brightness_scale: 254
  effect: true
  effect_list: 
    - "blink"
    - "breathe"
    - "okay"
    - "channel_change"
    - "finish_effect"
    - "stop_effect"
