- platform: template
  lights:
    book_light: # Simulate a light for the Sonoff connected inside the Book
      value_template: "{{ is_state('switch.sonoff_10004cf9ff', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
          entity_id: switch.sonoff_10004cf9ff
      turn_off:
        service: homeassistant.turn_off
        data:
          entity_id: switch.sonoff_10004cf9ff
