title: B&B Home

views:
  - path: default_view
    title: Overview
    icon: 'mdi:home'
    badges:
      - entity: person.andrea
      - entity: person.erica
      - entity: sun.sun
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Luci
            cards:
              - type: light
                entity: light.lampada_sala
              - type: light
                entity: light.book_light
              - type: light
                entity: light.shelly_shsw_1_f431b1
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                title: Elettrodomestici
                cards:
                  - type: button
                    entity: switch.tv_sala
                    name: TV Sala
                    icon: mdi:television
                    tap_action:
                      action: call-service
                      service: script.turn_on
                      service_data:
                        entity_id: script.tv_sala_power_on_off
                  - type: button
                    entity: switch.tv_cucina
                    name: TV Cucina
                    icon: mdi:television
                    tap_action:
                      action: call-service
                      service: script.turn_on
                      service_data:
                        entity_id: script.tv_cucina_power_on_off
              - type: horizontal-stack
                cards:
                  - type: button
                    entity: binary_sensor.washing_machine_status
                    icon: mdi:washing-machine
                    name: Lavatrice
                    state_color: true
                  - type: button
                    entity: binary_sensor.dryer_machine_status
                    icon: mdi:tumble-dryer
                    name: Asciugatrice
                  - type: button
                    entity: vacuum.mi_roborock
      - type: vertical-stack
        title: Stato casa
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.mi_t_582d343415fe
                name: Temperatura
              - type: sensor
                entity: sensor.mi_h_582d343415fe
                name: Umidità
          - type: entities
            entities:
              - type: custom:multiple-entity-row
                entity: sensor.home_recycling
                name: Spazzatura
                icon: mdi:delete-variant
                hide_state: true
                primary:
                  entity: sensor.home_recycling_types
                  name: Raccolta
          - type: picture-entity
            entity: camera.soggiorno
      - type: vertical-stack
        title: Meteo
        cards:
          - type: entities
            entities:
              - sensor.forecast_today_summary
              - type: custom:multiple-entity-row
                entity: sensor.dark_sky_temperature
                name: Adesso
                hide_state: true
                primary:
                  entity: sensor.dark_sky_temperature
                  name: Temperatura
                secondary:
                  entity: sensor.dark_sky_humidity
                  name: Umidità
                tertiary:
                  entity: sensor.dark_sky_precip_probability
                  name: Pioggia
              - entity: sensor.forecast_temperatures
                type: custom:multiple-entity-row
                name: Giornata
                hide_state: true
                primary:
                  entity: sensor.dark_sky_daytime_high_temperature_0d
                  name: Temperatura
                secondary:
                  entity: sensor.dark_sky_overnight_low_temperature_0d
                  name: Umidità
      - type: entities
        title: Carichi
        show_header_toggle: false
        entities:
          - entity: switch.gosund_presa02
            type: custom:multiple-entity-row
            name: Lavatrice
            icon: mdi:washing-machine
            toggle: true
            hide_state: true
            primary:
              entity: sensor.gosund_presa02_energy_power
              name: Consumo
          - entity: switch.gosund_presa01
            type: custom:multiple-entity-row
            name: Asciugatrice
            icon: mdi:tumble-dryer
            toggle: true
            hide_state: true
            primary:
              entity: sensor.gosund_presa01_energy_power
              name: Consumo
  - path: media
    title: Media
    icon: 'mdi:play-network'
    cards:
      - type: entities
        title: TV Cucina
        show_header_toggle: false
        entities:
          - script.tv_cucina_power_on_off
          - script.tv_cucina_volume_up
          - script.tv_cucina_volume_down
          - script.tv_cucina_mute
          - script.tv_cucina_channel_up
          - script.tv_cucina_channel_down
          - script.tv_cucina_change_source
      - type: entities
        title: TV Sala
        show_header_toggle: false
        entities:
          - script.tv_sala_power_on_off
          - script.tv_sala_volume_up
          - script.tv_sala_volume_down
          - script.tv_sala_mute
          - script.tv_sala_channel_up
          - script.tv_sala_channel_down
      - type: entities
        title: Routine
        show_header_toggle: false
        entities:
          - script.tv_sala_open_amazon_video
      - type: media-control
        entity: media_player.echo_dot_studio
      - type: entities
        title: Dispositivi
        show_header_toggle: false
        entities:
          - device_tracker.iphoneandrea
          - device_tracker.ipadandrea
          - device_tracker.iphoneerica
          - device_tracker.ipaderica
  - path: network
    title: Network and Devices
    icon: 'mdi:desktop-classic'
    cards:
      - type: vertical-stack
        title: AlfredPi Monitoring  
        show_header_toggle: false
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.memory_use_percent
              - type: gauge
                entity: sensor.processor_use
          - type: entities
            entities:
              - sensor.last_boot
              - entity: sensor.home_assistant_installed
                type: custom:multiple-entity-row
                name: Home Assistant
                hide_state: true
                primary:
                  entity: sensor.ha_upstream_version
                  name: Upstream
                secondary:
                  entity: sensor.ha_installed_version
                  name: Installed
              - type: weblink
                name: GitHub Releases
                url: https://github.com/home-assistant/home-assistant/releases
                icon: mdi:home-assistant
